### PR TITLE
error bars

### PR DESCRIPTION
**Pull request by MarvinT**
Hey,

Copying over the PR from https://github.com/danich1/annorxiver/pull/1
Not sure if I need to rebase it.

The only thing I've done here is add error bars the the bar plot in 4c. I wanted to set the xlim min value to 0 but I'm not well enough versed in p9 ... Up to you if you think it adds to the point of the figure or just unnecessarily clutters it.

I was trying to get publication_delay_experiment.ipynb running but it references /pmc/word_vector_experiment/output/ which isn't in the repo :( and I definitely don't want my experiments to delay you publication timeline :p

If you think getting a version of 4a with a hexbin or a 4b as a vertical ridgeplot would be useful, let me know how to get the /pmc/word_vector_experiment/output files and I can rush some over.
I was also thinking it would be fairly reasonable to remove papers with negative time to publication from the dataset.

Also, what are the requirements/protocol to get added as an external collaborator to the Greenelab slack. It might make it a bit faster to communicate.

### CODE REVIEW

**Comment by danich1** [comment]
>Copying over the PR from danich1#1
Not sure if I need to rebase it.

Feel free to close the other PR you opened under my github handle version. Rather any changes just go to the greenelab version instead.  

>I was trying to get publication_delay_experiment.ipynb running but it references /pmc/word_vector_experiment/output/ which isn't in the repo :( and I definitely don't want my experiments to delay you publication timeline :p

Yeah. Github hates any file that is greater than 2GB, so I couldn't put them on the repo even if I wanted to.  I should have saved the output files so you could load them. 🤦 I'll generate those output files so you can rework your code with them. Will push them towards your branch.

>Also, what are the requirements/protocol to get added as an external collaborator to the Greenelab slack. It might make it a bit faster to communicate.

@cgreene ☝️

**Comment by danich1** [comment]
[preprint_published_distances.xlsx](https://github.com/greenelab/annorxiver/files/5548482/preprint_published_distances.xlsx)

So.. github doesn't allow tsv to be uploaded. Converted the file you needed to excel. Feel free to export excel to tsv to make life a bit easier for you. Also, if you upload the file please keep it as tsv.

>4a with a hexbin or a 4b as a vertical ridgeplot 

If 4a looks better as a hexbin feel free to change it. 
So catch with ridgeplot (4b) is that I need to keep the y axis as publication time and x axis as version count. (I want to keep the regression line along with the figure.) If there is a way to accomplish this task or a way to keep all info together feel free to change.

**Comment by MarvinT** [comment]
Hey @danich1 ,
Made a couple plot alternatives for your consideration. The big thing I've learned from this exercise is that I should really learn plotnine. The code to construct your plots looks so much neater than in matplotlib/seaborn.

I was able to create a vertical ridgeplot and it looks pretty nice for 1-6 versions, but the data above 7 is too sparse to look good. If I set individual bandwidths or something I might be able to get a better version but I stopped after getting this far:
image
But maybe a violin or boxen plot might be just as affective, also included in https://github.com/MarvinT/annorxiver/blob/figure_tweaks/biorxiv/publication_delay_experiment/publication_delay_experiment_mt.ipynb.

At the bottom of the notebook I also played around with some hexbin versions of the distribution plot. I'm not convinced the marginal plots are useful.

image

If we want to stick with square bin plot, it might be nice to reformat the color bar to have the log spaced tick marks from my figures.

But I know figure aesthetics is largely down to personal preference, so these serve more of an intermediate alternatives and if any interest you I can try to polish them up a bit.

Let me know what you think,
Thanks,
~Marvin

**Comment by danich1** [comment]
These figures look awesome!! Thanks for doing this.

>Made a couple plot alternatives for your consideration. The big thing I've learned from this exercise is that I should really learn plotnine. The code to construct your plots looks so much neater than in matplotlib/seaborn.

 Yeah I converted to plotnine as I'm a really big fan of neat and quick to implement code.

>At the bottom of the notebook I also played around with some hexbin versions of the distribution plot. I'm not convinced the marginal plots are useful.

I saw them I think we could just do without them as the color shade should give the reader the same message.  If possible can you invert the hexagon plot? I kind like the high density values to have bright colors and low density colors have a darker tone.

>I was able to create a vertical ridgeplot and it looks pretty nice for 1-6 versions, but the data above 7 is too sparse to look good. If I set individual bandwidths or something ...
> But maybe a violin or boxen plot might be just as affective...

 I'm a bit torn as I like the side ridgeplot; however it will be difficult to plot a line on top of it. I think I'll switch to your violin plots as they look neater than my simple box plot. Just do me a favor and save these plots as svgs. I'll tweak the manuscript panels in another PR.

**Comment by MarvinT** [comment]
I can add the line in but I'm still concerned about the KDE being wonky for versions >7
image

any other modifications to the violin plot like days elapsed in year intervals?
Do you prefer spaces between the hexbins or not?

**Comment by danich1** [comment]
>I can add the line in but I'm still concerned about the KDE being wonky for versions >7

Yeah lets go with violin plot. This plot is cool nonetheless!!

>any other modifications to the violin plot like days elapsed in year intervals?

Keep it as days elapsed as I like to be consistent on the units

>Do you prefer spaces between the hexbins or not?

Don't think it is necessary, but if you want to add spaces let me know.

**Comment by MarvinT** [comment]
oh, I also excluded all preprints with a negative time to publication for these plots and regression.

**Review by danich1 — APPROVED** [review]
LGTM! Thanks again!

**Comment by danich1** [comment]
Let me know when good to merge.

**Comment by MarvinT** [comment]
All ready to merge.

**Pull request merged**
